apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
  namespace: video-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - name: mediamtx
        image: bluenviron/mediamtx:1.15.6
        ports:
        - containerPort: 8554
---
apiVersion: v1
kind: Service
metadata:
  name: mediamtx-service
  namespace: video-pipeline
spec:
  selector:
    app: mediamtx
  ports:
    - protocol: TCP
      port: 8554
      targetPort: 8554
  type: ClusterIP
