apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc
  namespace: video-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc
  template:
    metadata:
      labels:
        app: webrtc
    spec:
      containers:
      - name: webrtc
        image: your-webrtc-image:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-service
  namespace: video-pipeline
spec:
  selector:
    app: webrtc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
